### ISSUE TITLE
Finding if a Number is prime or not .. Ruby kickstarter 2:6

### ISSUE THREAD

**Issue by abitravers1989** [makersacademy/problem-solving#100]
hi all, :-)

I am doing ruby kickstarter session 2 challenge 6 which asks:

Write a method named prime_chars? which takes array of strings
 and returns true if the sum of the characters is prime.
 Remember that a number is prime if the only integers that can divide it with no remainder are 1 and itself.

 Examples of length three
 prime_chars? ['abc']             => true

This is my answer, which is apparently wrong but I can't understand what i have done wrong .. can anyone else spot it please? 

class Integer

  def is_prime?
      is_prime = true
        for i in 2..(self-1)
          if (self % i) ==0
            is_prime = false
          end
        end

      if is_prime
          puts "true"
        else
          puts "false"
        end
    end

    def prime_chars?(strings)
      strings.join.length.is_prime?
    end

  end

prime_chars? ('abcd') 
prime_chars? ['abcd']

Thanks

**Comment by nick-otter** [comment]
Hey Abi, 

I was just working through this one too!  What did the error message you received say?

N

**Comment by abitravers1989** [comment]
it is a no-method error:

6_array.rb:41:in `<main>': undefined method `prime_chars?' for main:Object (NoMethodError)

**Comment by nick-otter** [comment]
Just had a look, have you been using rake to test? Or have you been testing using the two lines at the bottom: prime_chars? ('abcd'), prime_chars? ['abcd'].

If you've been using the two lines at the bottom to test, the reason why the method is undefined is because you've nested your prime_chars? function inside your Integer class  - so it's just an instance method of the class Integer. So to call it outside of the class, you'd have to write: Integer.prime_chars?('abcd'). Hope that's helpful at all!! I didn't nest my method prime_chars? in a class, just left it as is - wasn't sure if the rake tests would tolerate creating a new class!

Based on this info: https://stackoverflow.com/questions/2527830/ruby-calling-class-method-from-instance

**Comment by abitravers1989** [comment]
OO thank you so much ... so i tried that and it still doesn't work ... and i have tried removing the class part and again it still doesn't work .. either on rake or by testing the bottom lines .. I really can't see the difference in principal between it and the solution itself ... I feel like maybe I am not deleting the class container properly or something. Thank you so much for your help 👍

**Comment by abitravers1989** [comment]
def is_prime?
      is_prime = true
        for i in 2..(self-1)
          if (self % i) ==0
            is_prime = false
          end
        end

      if is_prime
          puts "true"
        else
          puts "false"
        end
    end

def using_it(strings)
    p  strings.join.length.is_prime?
end


using_it('abcd')

**Comment by stephengeller** [comment]
Hey! So I can't immediately spot what's going wrong with this code, but copying it into my IDE showed up with an error on line 3 (undefined method '-') which points towards the self-1 bit. Has that been successful in iterating through i until the end of the number? It looks like that method doesn't understand that self is an integer, as I think it would otherwise understand '-' to function with it.

I think if you tried to change that to something else, that might solve something. The example used the  .upto method, which I used as well after fumbling around a lot. I'm not sure how to do it without getting rid of the self function, but if you added an argument to the is_prime? function - ie is_prime?(strings) - then just assigned the output of strings.join.length to a new variable within , then integrating that new variable into your method should work out fine. You can just rename the method itself as prime_chars?(strings) and pass whatever you want through it, that worked for me with the rakes. It has the added bonus of getting rid of the need for an extra method, but doesn't use the self method which I would love to understand more if I could...

Don't know how to help while using the self method though :( Sorry!

**Comment by abitravers1989** [comment]
Thank you so much! Ok I will try using the .upto method so I can get rid of self ... I would be interested to know why self won't work in this situation so i'll mark it as something to find out ... I will let you know the answer too once I get round to it. Thank you so much for your help!
