### ISSUE TITLE
Issue with student-directory exercise

### ISSUE THREAD

**Issue by Marcus-UK** [makersacademy/problem-solving#109]
Hi All, don't know if anyone can offer some guidance on solving this issue. I'm on the extra exercises of the student-directory and I'm struggling with the following:

"Modify your program to only print the students whose name begins with a specific letter."

I'm currently trying to modify the following method:

def print_students(students)
  students.each_with_index do |student, index|
  student. "#{index + 1}. #{student[:name]} (#{student[:cohort]} cohort)" 
     end

My initial thought was to do the following:

def print_students(students)
 students.each_with_index do |student, index|
 student[0] == "A" ? "#{index + 1}. #{student[:name]} (#{student[:cohort]} cohort)"  : nil
    end

but this isn't returning anything, even when I enter a name beginning with A in the student-directory program. Any thoughts?

**Comment by KKOA** [comment]
Hi Marcus, I see several problems with the code above. 
First of all your missing the end statement for the **each_with_index's block** . Without this, you will get a syntax error.

Secondly, you are pointing to a key that does not exist inside the **each_with_index's block**.  
student is holding a hash like this 
{:name=>"Dr. Hannibal Lecter", :cohort=>:november}
You cannot use a position with a hash to get a value. You have to use its keys.

To get the first letter of the student's name you can use this
student **[:name]** [0]

Thirdly, I would use **if statement** rather than the **ternary operator**. There is no point output nil.
Replace
student[0] == "A" ? "#{index + 1}. #{student[:name]} (#{student[:cohort]} cohort)" : nil
with
if student[0] == "A"
puts "#{index + 1}. #{student[:name]} (#{student[:cohort]} cohort)"
end

Fourthly, there is no output statement. The method is meant to output to something to the screen
