### ISSUE TITLE
Error when creating a new remote

### ISSUE THREAD

**Issue by jpsanders101** [makersacademy/problem-solving#111]
I'm attempting to create a new remote to connect a new Github repo with a local repo.

I've initialised the local directory with git. I used...

`remote add origin git@github.com:jonsanders101/learn-to-program.git`

To create an origin. However when I used the following command...

`git push -u origin master`

I received this error...

`error: src refspec master does not match any.
error: failed to push some refs to 'git@github.com:jonsanders101/learn-to-program.git'`

Any ideas?

**Comment by andyrow123** [comment]
What does 'git status' say? Have you added & committed everything?

**Comment by jpsanders101** [comment]
Ah - I only had an empty directory until now. I've just created an empty test.txt, committed that, and that has now allowed me to push to github. Is the lesson here that you can't use a remote to link git and github until there is an actual file in the repo?

**Comment by andyrow123** [comment]
I have a feeling it's more that you have an initial commit before you can push anything. I ran across this error a while back and this was the solution I found. I have tried to look for an explanation but have found none. I assume it could be due to missing tree data in your .git directory but I can not be sure.

When you try do  'git log' on an initialised but not committed repo you get:

fatal: your current branch 'master' does not have any commits yet

I assume pushing does not like this either. 

Sorry for the vague response!

to get around this I always:

git init
git add README
git commit -m "Initial Commit"

when starting on a new repo with no files
