### ISSUE TITLE
Chapter 8 question1

### ISSUE THREAD

**Issue by AntonioDaria** [makersacademy/problem-solving#158]
Hi Guys, I am having some problem designing my hash , containing an array of values, I had the following in mind but cannot get my head around it, any suggestion?
```
points_system = {
  0 => [" "]
  1 => ["E", "A", "I", "N", "R", "T", "L", "S", "U"],
  2 => ["D", "G"],
  3 => ["B", "C", "M", "P"],
  4 => ["F", "H", "V", "W", "Y"],
  5 => ["K"],
  8 => ["J", "X"]
  10 => ["Q", "Z"]
}
```

**Comment by afaraone** [comment]
A hash should work fine here. But you should check your commas.
I made a separate hash entry for each letter, but grouping them in an array per value could work as well.
One other thing, I think you should use the alphabet letters as the key for your hashes.
So `points_system["K"]` would return `5`, rather than vice versa.
I feel like hashes should be based on the idea that you know what your key is already, and are looking for the value. In this example, you already have the letters and are looking for the score. (hope that makes sense lol)

**Comment by FlorenceHapgood** [comment]
Hi Antonio, I also used letters as keys and numbers as values, and created a new key for each letter. When I tried it your way I couldn't get it to work...

**Comment by AntonioDaria** [comment]
```
puts "Insert a word "
word = gets.chomp
arr = word.split("")

points_system = {
  0 => [" "],
  1 => ["E", "A", "I", "N", "R", "T", "L", "S", "U"],
  2 => ["D", "G"],
  3 => ["B", "C", "M", "P"],
  4 => ["F", "H", "V", "W", "Y"],
  5 => ["K"],
  8 => ["J", "X"],
  10 => ["Q", "Z"]
}
p arr
print points_system
```
i now have this piece of code which gives me the hash and an array with the letter i will be looking for to get the total, but I am not so sure where do i go from here,
any idea?

**Comment by FlorenceHapgood** [comment]
Hey Antonio, so I don't think that it will work with the has as it is, I think maybe you might need the letters as keys and numbers as values, and do each one separately, and then you need to find a way to go through your array item by item and match it with the hash keys...does that help?

**Comment by FlorenceHapgood** [comment]
*hash as it is

**Comment by afaraone** [comment]
You need to use a method that will check through each of the elements of `arr`. (Hint: I have just used the name of it in my previous sentence :) )
