### ISSUE TITLE
The Supermarket Queue kata -  

### ISSUE THREAD

**Issue by anaalta** [makersacademy/problem-solving#22]
Hey all, I am stuck with this one and need some help: https://www.codewars.com/kata/the-supermarket-queue/train/ruby. I am passing the tests, so I think I covered all possible situations. But I have an error. 
So here's the code:

```
def queue_time(customers, n)
#if we have 0 customers, return 0
  if  customers.length == 0
  return 0
#if no of registers > no of customers, longest time is the total time  
  elsif customers.length <n 
    return customers.max
#if there is one register, the sum of each is the total time
  elsif n==1 
    sum = 0
    customers.each { |a| sum+=a }
    return sum
  else
#for the first n number of customers, the time is the max time, we store that
    qtime = 0
    for i in 1..n do
       if customers[i] > customers[i+1]
         qtime = customers[i]
       end
      #we remove from the array the first n elements, as those customers finishedd
      customers.shift(n)
    end
    #we return qtime + running the whole script again
    return qtime + queue_time(customers, n)
  end
end
```

And here's the error:

```
`>': comparison of Fixnum with nil failed (ArgumentError)
	from `block in queue_time'
	from `each'
	from  `queue_time'
	from  `queue_time'
	from  `block in 
'
	from  `block in describe'
	from  `measure'
	from  `describe'
	from  ``
```

Any ideas? Thanks!

**Comment by JayWebDevCom** [comment]
Hi, if you run the code below in your IDE I think it shows that there comes a time where the `1..n` loop will be looking for a customers array element which will not be there, explaining the `failed comparison of Fixnum with nil`.

I know that you tried to avoid that with the `elsif customers.length < n` so I know that you didn't want that part of the code to be executing.

I think that the code skips through when `customers.length` is equal to `n`, and then in your for loop, when `i` gets to `n` (maybe even before that) you are looking for a `customers[i+n]` that doesn't exist because the greatest _index_ of customers will be `n-1`.

Also, did you mean to `.shift(n)` ? i.e. remove `n` number of elements from front of the array?

I hope my debugging attempt helps. :)

```
def queue_time(customers, n)
#if we have 0 customers, return 0
  if  customers.length == 0
  return 0
#if no of registers > no of customers, longest time is the total time  
  elsif customers.length < n
    return customers.max
#if there is one register, the sum of each is the total time
  elsif n==1 
    sum = 0
    customers.each { |a| sum+=a }
    return sum
  else
#for the first n number of customers, the time is the max time, we store that
    qtime = 0
    for i in 1..n do
puts "i is #{i}"
puts "n is #{n}"
puts "Customers length is #{customers.length}"
      #we remove from the array the first n elements, as those customers finishedd
      customers.shift(n)
    end
    #we return qtime + running the whole script again
    return qtime + queue_time(customers, n)
  end
end
  ```

**Comment by anaalta** [comment]
@JayWebDevCom Thank you so much! It did help! You're right, the biggest index is n-1. And within the same for loop, there was an if without an else! Now it works, all good!
