### ISSUE TITLE
Directory.rb Step 8 exercise 2 issue when using code in project, works fine on its own. 

### ISSUE THREAD

**Issue by BertZZ** [makersacademy/problem-solving#33]
![test](https://cloud.githubusercontent.com/assets/26028408/24511866/ceceea6a-1564-11e7-8d9c-0c6ef8056f20.jpg)

As you can see this code works fine in this case however when I put it into the directory.rb project i get this error: 

![error](https://cloud.githubusercontent.com/assets/26028408/24511963/279c06f0-1565-11e7-9864-fde1bf22ceb4.jpg)

Anyone give me some advice that would point me in the right direction?

**Comment by BertZZ** [comment]
Sorted it once I realised it was now a hash not an array :P

**Comment by anaalta** [comment]
My 2 pennies: since your issue is with the each method, I am assuming that you apply your student by letter method to two different objects. The first works, because each works with arrays. But when you call it on a hash, I think you should have both key and value after the do part. Hope it'll help...
