### ISSUE TITLE
premission denied

### ISSUE THREAD

**Issue by jjadeseravla** [makersacademy/problem-solving#37]
Hi,
 I'm having a trouble uploading whats in my terminal onto github.  my terminal keeps telling me my permission is denied.

remote: Permission to makersacademy/clmystery.git denied to jjadeseravla.
fatal: unable to access 'https://github.com/makersacademy/clmystery.git/': The requested URL returned error: 403

what could be the cause of this?

Thanks in advance

**Comment by michaelbjacobson** [comment]
Hi Jade, which step are you on in the CL mystery? Can you please post the command that you're trying in your terminal?

**Comment by marioribeiro** [comment]
You need to fork the repository. You are probably trying to push changes to makersacademy/clmystery.git and you don't have permissions to do that.

1) Fork https://github.com/makersacademy/clmystery
2) Next you need to download those files to your machine so that you can edit them. To do that you must clone your forked repository (Instructions: https://help.github.com/articles/cloning-a-repository/)

**Comment by michaelbjacobson** [comment]
@jade_alvares did you see Mario's reply? Have you forked the clmystery from the original Makers Academy repo?

**Comment by michaelbjacobson** [comment]
Hi Jade, if you've forked the repo and your forked version to your machine can you please post the command that you're trying on here for us to see?

**Comment by marioribeiro** [comment]
After you fork https://github.com/makersacademy/clmystery you can then edit your local repository the use the updated remote. There are a few ways of doing this:

a) edit .git/config and update [remote "origin"]
b) remove the existing remote and add a new one via CLI
- https://help.github.com/articles/removing-a-remote/
- https://help.github.com/articles/adding-a-remote/

**Comment by michaelbjacobson** [comment]
*cloned your forked version
