### ISSUE TITLE
[ruby-kickstart 1:7] - accidentally assigning value to a variable?

### ISSUE THREAD

**Issue by KyeBracey** [makersacademy/problem-solving#40]
(Apologies for the bad title, I was struggling for the right words - I'm not asking for help to solve this challenge, which I've since done, but trying to figure out why my error did what it did.  I know all I should really take from this is "just type your code properly and it'll be fine", but now it's bugging me!)

Hey folks,

While working through the ruby kickstart challenges I made a typo, and started wondering why it affected my output the way it did.  I couldn't figure it out myself, nor could I find the answer on Google, so maybe one of you might be able to shed some light:

Here's a screenshot of my broken code - the error is on line 16 where I accidentally assign a value to a variable instead of checking if the variable is equal to something.

![image](https://cloud.githubusercontent.com/assets/25885650/25143814/bae323be-2463-11e7-9046-1947ee245e42.png)

Here's one with the typo fixed for comparison (I know this doesn't pass any of the other tests and could be a lot more efficient!).

![image](https://cloud.githubusercontent.com/assets/25885650/25143816/c0505196-2463-11e7-8d31-d282bd19dfd7.png)

So it looks like my typo is causing the method to give me a string with every even-numbered index removed.

Is my typo actually assigning a value to this variable and that's what is causing strange things to happen?  If so, is it only local within the scope of that "if" statement and then it's forgotten about on the next iteration?  If not, what is happening here?

Many thanks,
- Kye

**Comment by kkavita92** [comment]
Hey Kye, 

What I think is happening is ```i = "r"``` will always be true since it is always going to be possible to assign a value to ```i```. Hence, for your first iteration, for example, ```check``` will be equated to ```true``` as will be the case throughout your code. For the second iteration however, your 'if' statement comes into play first (due to control flow) and pushes the value into your string. This process repeats, causing alternate characters to be returned. 

I don't think the fact that you accidentally assigned a value to ```i``` has any impact on subsequent iterations as you've pointed out.

**Comment by KyeBracey** [comment]
Aha, got it!  I didn't consider that `i = "r"` was evaluating to `true` (that was fun to mess around in irb with). Then it's just the control flow listening to my `check` variable.  That makes perfect sense now - thanks 👍
