### ISSUE TITLE
Explanation for BeerSong in Ruby-Kickstart (Challenge 2:11)?

### ISSUE THREAD

**Issue by bannastre** [makersacademy/problem-solving#41]
*SPOILER ALERT* - This is from the solution to the BeerSong challenge in Ruby-Kickstart (Challenge 2:11) 

Can anyone help explain what is happening in the code here, specifically what effect does the `[num/10]` part have on the array of strings `%w`?

 `%w(zero ten twenty thirty forty fifty sixty seventy eighty ninety)[num/10]`

Later in the code, it appears to be called with `#{number_string num/10*10}`... Full code for the solution is [here](https://github.com/JoshCheek/ruby-kickstart/blob/master/session2/solved/11.rb)

**Comment by SiAshbery** [comment]
Ok, so I think this is what's going on here: Bare in mind I'm on this section too and going through the solution to try and understand it.

The %w(zero ten etc.....) is a quick way of defining an array and the [num/10] at the end is referring directly to the index number of each item in that array.

the num is the number that's being passed in that we want to translate to letters for. The reason that it's doing num/10 is that in this block we're looking for is a multiple of 10  so if num = 30 then [num/10] = [3] Which will give us the fourth* entry in the array, "thirty"

It's the same thing that's going on in the array above but it's looking for the translation to any value from units to the teens so [] can just reference the value of num directly. [1] = one [2] = two [17] = seventeen etc.

I'm still puzzling over how it works (and why it is num/10*10 rather than num/100) But the last part must be a way of combining the translated numbers to produce any number between 20 and 99 than isn't a clean 10.

 *edit*

I'm not great with maths but for "#{translate n/10*10}-#{translate n%10}".downcase i'm thinking the following: Since each instance of translate here is being interpolated into the string the first method must extract the tens value and the second, the unit. The second instance makes more sense to me. As any number > 10 divided by 10 will leave behind the last digit as a remainder. I.e. 11 % 10 = 1 37 % 10 = 7 80 % 10 = 0

The first block still confuses me though. I know what it's doing, just not how

**Comment by kkavita92** [comment]
The reason why it's not num/100 is because it's meant to be (num/10)*10. As has been pointed out, when num = 53 for example, the method breaks it down into calling ```translate``` on fifty and three (line 39). You can't obtain 50 directly so you are going to divide num by 10 which will give you 5 and then multiply it be ten so when you call ```translate``` on it, it will evaluate it according to line 37 of the solution instead of line 35.

**Comment by SiAshbery** [comment]
AH! yeah that totally clicks now, thanks!

**Comment by bannastre** [comment]
Thanks @SiAshbery, that makes more sense now! And @kkavita92, that explains why the call is like:
 `#{translate n/10*10}-#{translate n%10}`

Thanks guys, you bunch of codey-wizards!
