### ISSUE TITLE
Class Initialisation query

### ISSUE THREAD

**Issue by charlottebrf** [makersacademy/problem-solving#44]
Hello,

I have another query about classes, specifically class initialization (strongly based on one of the challenges...). I've put my questions in the example screenshot of the 'Cat' class. 

Having googled around I see that the method  #containing @anniversary += 1  is a ruby shortcut for adding 1 to the value of the instance variable @anniversary. 

My question is why do I want to initialize @anniversary with a pre-set value of 1 instead of initializing it in the same way as @cat & @breed in the constructor & attr_accessor ?

 Is it something to do with being an optional Instance variable that can be invoked by the receiver but isn't a part of the Cat class instance? I.e. birthday wouldn't be inherited as it's not in the constructor?

![classes query](https://cloud.githubusercontent.com/assets/16884984/25273109/46339b9a-2682-11e7-8aa4-05dc2dac3f4f.png)

**Comment by AaronRodrigues** [comment]
Every time the anniversary method is being called, its instance variable @anniversary is *incremented* by 1. This is to return the number of anniversaries after a certain amount of time. Its a way of keeping count of the anniversaries( after every year I'm assuming). 

Every time the method, anniversary is called, it sort of means that a year has passed and the number of anniversaries has increased by 1.

I'm following the Chris Pine book,  I'm not sure what your program here is supposed to do, which is why I'm not sure how to answer your second question.

**Comment by charlottebrf** [comment]
Thanks @AaronRodrigues that's a really helpful insight, that it's a counter of sorts.  So rather than simply giving a year as an anniversary, it will keep track of the number of years as you say. 

I will keep playing around with it to better understand how this works, and when it's helpful to use.

Much appreciated!

**Comment by bannastre** [comment]
Hey, so in your code example you're initializing the class with the instance_variables `@breed` and `@colour` only. 

You then have a separate method called anniversary and that, as @AaronRodrigues says, is behaving like a counter for the instance_variable `@anniversary`. 

Every new Cat class object will have a breed and a colour but not an anniversary until you call that method on the object, for example:

`Felix = Cat.new ('tabby', 'blue')`  =>  Creates a new Cat object called Felix
`Felix.anniversary` => increases the value of Felix's anniversary by 1

I guess you're trying to say that the anniversary will always be the age + one year? One other thing, I still think this will error because you don't have a variable for `age` or `anniversary` defined... 

Hope that helps

**Comment by charlottebrf** [comment]
Thanks a lot @bannastre ! That's also really helpful, shed some more light on the query.

Yes you're right I didn't create any new Cat instances, thanks for noting. I didn't bother here as was playing around with a Cat class version of a ruby kickstart version from challenges 2. I don't know if you did that one but it wasn't clear to me in instructions for 2:10 challenge that we needed a count on birthday- was trying to understand it with this example.

Anyway thanks to you both that helps explain why you'd use a += with an instance variable- much appreciated! :)

**Comment by bannastre** [comment]
Ah yeah - that's a confusing exercise. He's trying to say that on the object's next birthday they will be "age+1" years old so the birthday method just returns `@age += 1`.

I'm finding some of these pretty confusing too but I suppose it's getting us looking for the answers...

**Comment by charlottebrf** [comment]
Cool thanks a lot @bannastre 👍  closing the issue now that's helped.

**Comment by lubosmichalic** [comment]
Hi Charlotte, 
I realized that you've already closed this one, but wanted to chime in as I just struggled through this one myself. As both @AaronRodrigues and @bannastre have already mentioned , the @anniversary method is not part of the initiliaze method because it is a method that changes one of the parameters of the object after it had been initialized. The exercise wasn't very clear and I tried initializing the object with all three variables myself. 
![screen shot 2017-04-21 at 18 39 51](https://cloud.githubusercontent.com/assets/26767476/25289716/b83b86cc-26c2-11e7-9c31-899e1a95d2b8.png)

Which tipped me off about only having the name and age as arguments in the initialize method.
Decided that I needed some more help, so I let another error give me tips on how to proceed.

![screenshot](https://cloud.githubusercontent.com/assets/26767476/25289781/f64664c8-26c2-11e7-90a6-e336214ce8c6.png)

Hope this little tid bit helps in some future exercises.

**Comment by charlottebrf** [comment]
That's really helpful thank you @lnmichalic , as your pics point out there even though the original instructions weren't that clear the error messages give the clues.

Thanks, I'll be sure to make sure I'm properly reading what they're telling me. 

Much appreciated!
