### ISSUE TITLE
Additional permissions not able to remove them

### ISSUE THREAD

**Issue by chuk-chuk** [makersacademy/problem-solving#59]
All permissions are displayed like this:  _rwxrwxrwx, however when I run this command I get: _rwxrwxrwx@ Apparently it means this: “+ (extend): extend security bit, this file have acl, cannot delete it”.  I've found the command to remove an ACL(access control list) from a folder and everything inside of it: chmod -R -N /path/to/folder. Still nothing happens, even when restarted my terminal session. Has anyone had similar issue or can help? 
![screen shot 2017-06-09 at 09 58 16](https://user-images.githubusercontent.com/17936895/26968784-2a6047ca-4cfb-11e7-854d-c2ef3d5d8b95.png)

**Comment by Benjamin-Hughes** [comment]
I did some googling, but this isn't something I've run into before. Looks like the "@" indicates that a file has extended attributes, rather than an ACL. Try using `xattr <filename>` to display the attributes for a file and then `xattr -c <filename>` to delete them. You can also check the man page for xattr if you want more info `man xattr` or the help file `xattr -h`. Hopefully that will sort it for you.

**Comment by oleglukyanov** [comment]
@ shouldn't be an issue to my knowledge.
If you do `xattr -d <filename>` and then `xattr <filename>` — what you see then?

Also, if still not permitted to do something, you can try acting as a superuser `sudo <yourcommands>`

**Comment by chuk-chuk** [comment]
Great! It worked, thank you both @Benjamin-Hughes & @oleglukyanov I got it wrong, assuming that I need to delete ACL...overgoogled I guess:-)
![screen shot 2017-06-09 at 22 57 25](https://user-images.githubusercontent.com/17936895/26995922-5ea0a54a-4d67-11e7-8582-a1de4591c0d0.png)
