### ISSUE TITLE
Help! Session 3 Challenge 3

### ISSUE THREAD

**Issue by Nandhini31** [makersacademy/problem-solving#76]
def word_count(string)
  return_hash = {}
  new_array = string.split
  new_array.each do |i|
    return_hash[i.downcase] = new_array.count(i.downcase)
  end
  return return_hash
  end

works fine on repl.it. But fails rake testing with error

1) word_count returns {"the" => 2, "dog" => 1, "and" => 1, "cat" => 1} when given "The dog and the cat"
     Failure/Error:
       expect(word_count "The dog and the cat")
         .to eq "the" => 2, "dog" => 1, "and" => 1, "cat" => 1

       expected: {"the"=>2, "dog"=>1, "and"=>1, "cat"=>1}
            got: {"the"=>1, "dog"=>1, "and"=>1, "cat"=>1}

       (compared using ==)

       Diff:
       @@ -1,5 +1,5 @@
        "and" => 1,
        "cat" => 1,
        "dog" => 1,
       -"the" => 2,
       +"the" => 1,

     # ./session3/4-spec/3.rb:11:in `block (2 levels) in <top (required)>'

Finished in 0.03703 seconds (files took 0.22663 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./session3/4-spec/3.rb:10 # word_count returns {"the" => 2, "dog" => 1, "and" => 1, "cat" => 1} when given "The dog and the cat"

**Comment by ghost** [comment]
@Nandhini31 
ok, first of all thank you very much for giving me half of the answer to this exercise. I got stuck for like a couple of hours because of the Hash and pushing to hashes. Need to revise 

try this:

```ruby
def word_count(string)
	return_hash = Hash.new(0) #=> 1
	new_array = string.split
	
	new_array.each do |i|
		return_hash[i.downcase] += 1 #=> 2
	end
return_hash
end
```

Regarding 1, check this answer on SOF: https://stackoverflow.com/questions/35177845/whats-the-difference-between-hash-new0-and

```ruby
Hash.new(0) sets default value for any key to 0, while {} sets nil
```
I didn't know that so,  nil + 1 will throw an error.  
Hash.new(0) gives default value 0, therefore 0 + 1 = 1 and so on from here

--------------------

Regarding 2: What you have in your code above seems to work on the command line but fails the rake test. Don't know why, might be because how the test is made but honestly don't know

**Comment by Nandhini31** [comment]
ta @AlexSusanu
