### ISSUE TITLE
Using &block

### ISSUE THREAD

**Issue by paulmillen** [makersacademy/problem-solving#79]
This has been something I've struggled to get my head around.  I thought I understood the principle but being often unable to get the syntax to work means I probably don't.

if `file = file_option {|x| do something x}`

then

```
def file_option &block
  filename = STDIN.gets.chomp
  file = filename.empty? ? File.open(@default_file, "w") block : File.open(filename, "w") block
  return file
end
```
Is it possible to add the block argument to the File.open calls?  (in reference to Step 14-6 of this week's challenge.  Googling is getting me nowhere!

**Comment by aballal** [comment]
Ternary (from what I have seen) is usually used for single instructions following ? and :. You could possibly enclose multiple instructions in parenthesis and separate with ';' and use within ternary but I would rather use if/else in that case as it's more readable. In your code, you could use ternary for the filename alone and do the file opening as a next step that can then be enclosed in a do-end block. For instance...

Have a method that returns filename:
```
#some message to user to enter filename
filename = STDIN.gets.chomp
filename.empty? ? @default_file : filename #last instruction so that filename gets returned
```

In the calling method say load_students where you open the file instead of 
```
file = File.open(filename, "r")
#rest of the logic to read the lines and process it
```

code:

```
File.open(filename, "r") do |file|
  #same rest of the logic to read the lines and process it
end
```
You don't need file.close in this case.

Effectively you are passing your code that processes the file as a block to open method. When that happens it receives file as a parameter and that's why you can pipe in 'file'. 'file' is also closed when block ends. Here's the documentation from ruby-lang.

https://ruby-doc.org/core-2.2.0/File.html#method-c-open

Haven't tried out anything I have typed above, so I hope I haven't made any mistake. I hope this helps.

**Comment by paulmillen** [comment]
Thanks.  I can see how that's a more comprehensible structure. 

However, does this mean then that passing blocks as arguments doesn't allow you to use them to transfer that block to another method call?  So:

```
def example(arg,&block)
  block.call(arg)
end
```

will allow something like `example("hello") { |arg| puts arg } => "hello"`.  But you couldn't do:

```
def example(file,&block)
  File.open(file,w) block/&block/block.call 
end
```
Such that `example("students") {|row| puts "row"} would then pass the block to the end of the File.open call?

**Comment by aballal** [comment]
You can do but you will need to correct your code a little. However, the intention of having the do-end block was so that the file need not be explicitly closed. But that doesn't appear to happen when you do it this way.

Here's your example slightly modified:

```
def example(filename,&block)
  file = File.open(filename,"w")
  block.call(file,"Writing from block inside example method")
  #file.close
  file = File.open(filename,"r")
  STDOUT.puts file.readlines
end

example("students") {|file,row| file.puts(row)}
```
If the file indeed closed in block.call you would be able to read its contents and write it to the standard output. However run this code and you will see that nothing gets written to standard output. Now uncomment file.close and run it and you will see that you have the messages written into standard output. The reason it happens is because the file wasn't closed automatically in the block. When you have a do-end block following the file open, the file gets closed automatically.

```
def example(filename,&block)
  File.open(filename,"w") do |file|
    file.puts "Writing from block inside example method"
  end
  #file.close
  file = File.open(filename,"r")
  STDOUT.puts file.readlines
end

example("students") {|file,row| file.puts(row)}
```

**Comment by paulmillen** [comment]
Right, that's interesting.  Thanks for the illustration - this is really helpful!
