### ISSUE TITLE
Exercise 8:2 - First character of each element in array of strings

### ISSUE THREAD

**Issue by annalaise** [makersacademy/problem-solving#80]
I'm struggling to get my method to find the first character of each string element in the array `students` and print only these. I've tried searching all through the documentation / stack overflow and am having no luck. So far, my code looks like this (with the letter "a" hardcoded in, both up and down case): 

![image](https://user-images.githubusercontent.com/17883880/27430971-3622cc40-577d-11e7-83cc-45ed95d5ddfe.png)

The output in iTerm looks like this: 

![image](https://user-images.githubusercontent.com/17883880/27431031-8468cd50-577d-11e7-9ca5-468d1d0deb94.png)

I am probably missing something really simple, but welcome all help!

**Comment by i-hardy** [comment]
I think you're having an issue in the second line when you iterate over 'students'- remember each element of students is a two-part hash, but your code there is looking for the 0th indexed item of the whole hash rather than of the string value of the :name key.

For comparison, here's mine:

<img width="720" alt="screen shot 2017-06-22 at 12 06 10" src="https://user-images.githubusercontent.com/29146931/27431147-55f78a4a-5743-11e7-9127-0ef6b6a388b8.png">

**Comment by aballal** [comment]
Why is your print calling itself? You don't need recursion for this. Your if condition that checks for the first letter needs to be nested within the students.each loop. You can access the first character of name using student[:name][0] just like a regular string[0]. You can get user input in order to avoid hard coding. I hope that helps.

**Comment by annalaise** [comment]
Brilliant - thanks both - realised I was iterating over the whole hash rather than just name just now. All sorted! and removed recursion too. I am learning A LOT today! 😄
