### ISSUE TITLE
Check fails on clmystery

### ISSUE THREAD

**Issue by rolandosorbelli** [makersacademy/problem-solving#98]
Hi guys!

I have submitted my pull request for the Command Line Mystery of the first week of the pre course but I get a fail from The Travis CI. I have tried to submit it again editing the file and pushing it into my repo but nothing, it keeps failing. 

I am sure that the file is correct and so is its content: no clue why it's failing.

That's my pull request into the Makers Academy repo: https://github.com/makersacademy/clmystery/pull/623

Thank you in advance.
Rolando

**Comment by nick-otter** [comment]
Hi Rolando! 

Sorry for a slow response! If your read & edit permissions are correct, I think you've inputted/formatted the text in the wrong way - I did exactly the same thing! 

Try using echo to input the text into Jail.txt in the command line. I viewed the most recent commit "Murderer has been caught 4.0", the metadata for it reads: 1 lines (1 sloc) | 13 Bytes. 

If you use echo to input the text instead of manually inputting it outside of your command line the metadata will read: 2 lines (1 sloc) | 14 Bytes. It will be read correctly by The Travis CI if your read and edit permissions are correct as well. 

Hope that's helpful and makes sense! Here's a link to my reformatted jail.txt which passed: 
https://github.com/nick-otter/clmystery/blob/95f6ffc75ae25410582c5e8f55947b2e76ec5c29/jail.txt

**Comment by rolandosorbelli** [comment]
Hi Nick,

I have tried again using echo > jail.txt and again, it fails. The permissions should be fine: -rwxr--r--, so I've got all the permissions and the group and the others have just the reading permission. 
I really don't know what it can be D:

**Comment by nick-otter** [comment]
Hey,

Oh! That's frustrating.. and you've added the text without any additional spaces? If it's helpful, the permissions on my Jail.txt file are -rw-r--r--, but I think it should pass the test anyway with execute included. Sorry, I'm out of ideas too in that case!!

**Comment by rolandosorbelli** [comment]
Did the challenge again and this time it works. I will close the issue.

Thank you!
